### PR TITLE
Fix assignment upload to work with new code server

### LINKED ISSUE #388: Assignment Upload with new code server
Assignment can be uploaded, but cannot be checked instantaneously during the upload.

### PR DESCRIPTION
**Pull request by maheshgudi**
1. Fixes assignment upload to work the new tornado server. 
2. Closes #388

### CODE REVIEW

File: yaksh/static/yaksh/js/requesthandler.js [hunk 1]
```diff
@@ -126,19 +142,26 @@ $(document).ready(function(){
...
-
+}
+if (question_type == 'upload' || question_type == 'code') {
   $('#code').submit(function(e) {
     lock_screen();
+    if (question_type == "code"){
     var data = $(this).serializeArray();
+  }
+  else if (question_type == "upload"){
+    var data = new FormData($("#code").get(0));
```
Comment (prathamesh920) [inline yaksh/static/yaksh/js/requesthandler.js]: Just a suggestion.
Instead of get(),  we can pass form using document.getElementById, just for clarity.
